apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    name: db
  name: db
spec:
  storageClassName: my-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-060125c40d1d7edbe
    fsType: ext4
  # persistentVolumeReclaimPolicy: Retain
  # awsElasticBlockStore:
  #   volumeID: vol-060125c40d1d7edbe
  #   fsType: ext4
